# Generated by Django 3.0.5 on 2020-04-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('renouncement', models.BooleanField(default=False, verbose_name='Отказ')),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invites.Invite', verbose_name='Приглашение')),
            ],
        ),
    ]
