# Generated by Django 3.0.5 on 2020-05-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0005_auto_20200511_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='is_invite_to_class',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='is_invite_to_school',
        ),
    ]
