# Generated by Django 3.0.5 on 2020-04-12 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='main_teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='main teacher'),
        ),
    ]
