# Generated by Django 3.0.5 on 2020-04-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_', '0002_auto_20200412_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='main_teacher',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='char_class',
            field=models.CharField(max_length=2, verbose_name='char'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='number_class',
            field=models.IntegerField(verbose_name='number'),
        ),
    ]
