# Generated by Django 3.0.5 on 2020-04-15 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200415_1537'),
        ('class_', '0003_auto_20200412_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classmodel',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='char_class',
            field=models.CharField(max_length=2, verbose_name='Буква'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='number_class',
            field=models.IntegerField(verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School', verbose_name='Школа'),
        ),
    ]
