# Generated by Django 3.0.5 on 2020-04-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_', '0004_auto_20200415_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_.ClassModel', verbose_name='Класс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
    ]
