# Generated by Django 3.0.5 on 2020-04-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20200415_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
        migrations.AlterModelOptions(
            name='directer',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директора'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Школьник', 'verbose_name_plural': 'Школьники'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.Diary', verbose_name='Дневник'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='value',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.Student', verbose_name='Школьник'),
        ),
        migrations.AlterField(
            model_name='directer',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_app.Subject', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_app.Subject', verbose_name='Урок'),
        ),
    ]
