# Generated by Django 3.0.5 on 2020-05-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200415_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindSchoolTeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School', verbose_name='Школа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакт школы и учителя',
                'verbose_name_plural': 'Контакты школы и учителя',
                'ordering': ['-created'],
            },
        ),
    ]
